package com.nexus.enums;
public enum ActivityType {
    USER_LOGIN, USER_LOGOUT, PROJECT_CREATED, PROJECT_UPDATED, PROJECT_DELETED,
    PROJECT_ARCHIVED, TASK_CREATED, TASK_UPDATED, TASK_DELETED, TASK_ASSIGNED,
    TASK_STATUS_CHANGED, COMMENT_ADDED, TEAM_CREATED, TEAM_MEMBER_ADDED,
    TEAM_MEMBER_REMOVED, ATTACHMENT_UPLOADED, PROFILE_UPDATED, PASSWORD_CHANGED
}
