package com.nexus.enums;
public enum NotificationType {
    TASK_ASSIGNED, TASK_DEADLINE_REMINDER, TASK_STATUS_CHANGED,
    PROJECT_STATUS_CHANGED, COMMENT_ADDED, TEAM_MEMBER_ADDED, TEAM_MEMBER_REMOVED
}
